insert into currencies (entity, currency, code, numeric, minor_unit, withdrawal_date) values
('BULGARIA', 'Bulgarian Lev', 'BGN', '975', '2', NULL),
('CURAÇAO', 'Caribbean Guilder', 'XCG', '532', '2', NULL),
('EUROPEAN UNION', 'Euro', 'EUR', '978', '2', NULL),
('FAROE ISLANDS (THE)', 'Danish Krone', 'DKK', '208', '2', NULL),
('GEORGIA', 'Lari', 'GEL', '981', '2', NULL),
('GUAM', 'US Dollar', 'USD', '840', '2', NULL),
('KENYA', 'Kenyan Shilling', 'KES', '404', '2', NULL),
('MONGOLIA', 'Tugrik', 'MNT', '496', '2', NULL),
('SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA', 'Saint Helena Pound', 'SHP', '654', '2', NULL),
('SINT MAARTEN (DUTCH PART)', 'Caribbean Guilder', 'XCG', '532', '2', NULL),
('UKRAINE', 'Hryvnia', 'UAH', '980', '2', NULL),
('VENEZUELA (BOLIVARIAN REPUBLIC OF)', 'Bolívar', 'VEF', '937', NULL, '2018-08'),
('YUGOSLAVIA', 'New Yugoslavian Dinar', 'YUD', '890', NULL, '1990-01'),
('ARGENTINA', 'Argentine Peso', 'ARS', '032', '2', NULL),
('ETHIOPIA', 'Ethiopian Birr', 'ETB', '230', '2', NULL),
('FRENCH GUIANA', 'Euro', 'EUR', '978', '2', NULL),
('INTERNATIONAL MONETARY FUND (IMF)', 'SDR (Special Drawing Right)', 'XDR', '960', '-', NULL),
('IRAQ', 'Iraqi Dinar', 'IQD', '368', '3', NULL),
('KIRIBATI', 'Australian Dollar', 'AUD', '036', '2', NULL),
('MALI', 'CFA Franc BCEAO', 'XOF', '952', '0', NULL),
('MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP', 'ADB Unit of Account', 'XUA', '965', '-', NULL),
('MONTSERRAT', 'East Caribbean Dollar', 'XCD', '951', '2', NULL),
('NAMIBIA', 'Namibia Dollar', 'NAD', '516', '2', NULL),
('PAKISTAN', 'Pakistan Rupee', 'PKR', '586', '2', NULL),
('SAINT VINCENT AND THE GRENADINES', 'East Caribbean Dollar', 'XCD', '951', '2', NULL),
('TAJIKISTAN', 'Somoni', 'TJS', '972', '2', NULL),
('YEMEN', 'Yemeni Rial', 'YER', '886', '2', NULL),
('ANGOLA', 'Kwanza', 'AOK', '024', NULL, '1991-03'),
('SOUTHERN RHODESIA', 'Rhodesian Dollar', 'RHD', '716', NULL, '1978 to 1981'),
('VENEZUELA (BOLIVARIAN REPUBLIC OF)', 'Bolivar', 'VEF', '937', NULL, '2016-02'),
('YUGOSLAVIA', 'New Dinar', 'YUM', '891', NULL, '2003-07'),
('BRUNEI DARUSSALAM', 'Brunei Dollar', 'BND', '096', '2', NULL),
('FRANCE', 'Euro', 'EUR', '978', '2', NULL),
('GHANA', 'Ghana Cedi', 'GHS', '936', '2', NULL),
('LATVIA', 'Euro', 'EUR', '978', '2', NULL),
('LIECHTENSTEIN', 'Swiss Franc', 'CHF', '756', '2', NULL),
('SOMALIA', 'Somali Shilling', 'SOS', '706', '2', NULL),
('SUDAN (THE)', 'Sudanese Pound', 'SDG', '938', '2', NULL),
('WESTERN SAHARA', 'Moroccan Dirham', 'MAD', '504', '2', NULL),
('CURAÇAO', 'Netherlands Antillean Guilder', 'ANG', '532', NULL, '2025-03'),
('MARTINIQUE', 'French Franc', 'FRF', '250', NULL, '2002-03'),
('SAINT MARTIN', 'French Franc', 'FRF', '250', NULL, '1999-01'),
('SAN MARINO', 'Italian Lira', 'ITL', '380', NULL, '2002-03'),
('ZIMBABWE', 'Zimbabwe Dollar (old)', 'ZWD', '716', NULL, '2006-08'),
('ZIMBABWE', 'Zimbabwe Dollar', 'ZWR', '935', NULL, '2009-06'),
('BENIN', 'CFA Franc BCEAO', 'XOF', '952', '0', NULL),
('CABO VERDE', 'Cabo Verde Escudo', 'CVE', '132', '2', NULL),
('CENTRAL AFRICAN REPUBLIC (THE)', 'CFA Franc BEAC', 'XAF', '950', '0', NULL),
('CHILE', 'Chilean Peso', 'CLP', '152', '0', NULL),
('CONGO (THE DEMOCRATIC REPUBLIC OF THE)', 'Congolese Franc', 'CDF', '976', '2', NULL),
('CONGO (THE)', 'CFA Franc BEAC', 'XAF', '950', '0', NULL),
('SWITZERLAND', 'WIR Euro', 'CHE', '947', '2', NULL),
('ZZ04_Bond Markets Unit European_EUA-17', 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)', 'XBD', '958', '-', NULL),
('ALBANIA', 'Old Lek', 'ALK', '008', NULL, '1989-12'),
('BULGARIA', 'Lev A/62', 'BGK', '100', NULL, '1989 to 1990'),
('ESTONIA', 'Kroon', 'EEK', '233', NULL, '2011-01'),
('GEORGIA', 'Georgian Coupon', 'GEK', '268', NULL, '1995-10'),
('LATVIA', 'Latvian Ruble', 'LVR', '428', NULL, '1994-12'),
('TURKEY', 'Old Turkish Lira', 'TRL', '792', NULL, '2005-12'),
('ALBANIA', 'Lek', 'ALL', '008', '2', NULL),
('AMERICAN SAMOA', 'US Dollar', 'USD', '840', '2', NULL),
('ANTIGUA AND BARBUDA', 'East Caribbean Dollar', 'XCD', '951', '2', NULL),
('CHRISTMAS ISLAND', 'Australian Dollar', 'AUD', '036', '2', NULL),
('GRENADA', 'East Caribbean Dollar', 'XCD', '951', '2', NULL),
('GUINEA', 'Guinean Franc', 'GNF', '324', '0', NULL),
('JORDAN', 'Jordanian Dinar', 'JOD', '400', '3', NULL),
('LESOTHO', 'Rand', 'ZAR', '710', '2', NULL),
('MALAWI', 'Malawi Kwacha', 'MWK', '454', '2', NULL),
('SLOVAKIA', 'Euro', 'EUR', '978', '2', NULL),
('SWEDEN', 'Swedish Krona', 'SEK', '752', '2', NULL),
('TUVALU', 'Australian Dollar', 'AUD', '036', '2', NULL),
('ZZ09_Palladium', 'Palladium', 'XPD', '964', '-', NULL),
('BRAZIL', 'Cruzeiro', 'BRE', '076', NULL, '1993-03'),
('ECUADOR', 'Unidad de Valor Constante (UVC)', 'ECV', '983', NULL, '2000-09'),
('RÉUNION', 'French Franc', 'FRF', '250', NULL, '2002-03'),
('SAO TOME AND PRINCIPE', 'Dobra', 'STD', '678', NULL, '2017-12'),
('TURKMENISTAN', 'Turkmenistan Manat', 'TMM', '795', NULL, '2009-01'),
('ANGUILLA', 'East Caribbean Dollar', 'XCD', '951', '2', NULL),
('CAMBODIA', 'Riel', 'KHR', '116', '2', NULL),
('COOK ISLANDS (THE)', 'New Zealand Dollar', 'NZD', '554', '2', NULL),
('COSTA RICA', 'Costa Rican Colon', 'CRC', '188', '2', NULL),
('ECUADOR', 'US Dollar', 'USD', '840', '2', NULL),
('HAITI', 'US Dollar', 'USD', '840', '2', NULL),
('INDIA', 'Indian Rupee', 'INR', '356', '2', NULL),
('MONTENEGRO', 'Euro', 'EUR', '978', '2', NULL),
('NEW CALEDONIA', 'CFP Franc', 'XPF', '953', '0', NULL),
('NICARAGUA', 'Cordoba Oro', 'NIO', '558', '2', NULL),
('SAINT PIERRE AND MIQUELON', 'Euro', 'EUR', '978', '2', NULL),
('SRI LANKA', 'Sri Lanka Rupee', 'LKR', '144', '2', NULL),
('SURINAME', 'Surinam Dollar', 'SRD', '968', '2', NULL),
('TURKS AND CAICOS ISLANDS (THE)', 'US Dollar', 'USD', '840', '2', NULL),
('URUGUAY', 'Unidad Previsional', 'UYW', '927', '4', NULL),
('VIRGIN ISLANDS (BRITISH)', 'US Dollar', 'USD', '840', '2', NULL),
('ZZ11_Silver', 'Silver', 'XAG', '961', '-', NULL),
('GERMANY', 'Deutsche Mark', 'DEM', '276', NULL, '2002-03'),
('LESOTHO', 'Financial Rand', 'ZAL', '991', NULL, '1995-03'),
('ZZ05_UIC-Franc', 'UIC-Franc', 'XFU', NULL, NULL, '2013-11'),
('BANGLADESH', 'Taka', 'BDT', '050', '2', NULL),
('BRAZIL', 'Brazilian Real', 'BRL', '986', '2', NULL),
('FIJI', 'Fiji Dollar', 'FJD', '242', '2', NULL),
('HONDURAS', 'Lempira', 'HNL', '340', '2', NULL),
('MAURITANIA', 'Ouguiya', 'MRU', '929', '2', NULL),
('MONACO', 'Euro', 'EUR', '978', '2', NULL),
('PALAU', 'US Dollar', 'USD', '840', '2', NULL),
('PARAGUAY', 'Guarani', 'PYG', '600', '0', NULL),
('SEYCHELLES', 'Seychelles Rupee', 'SCR', '690', '2', NULL),
('ANGOLA', 'Kwanza Reajustado', 'AOR', '982', NULL, '2000-02'),
('AZERBAIJAN', 'Azerbaijanian Manat', 'AZM', '031', NULL, '2005-12'),
('CROATIA', 'Kuna', 'HRK', '191', NULL, '2023-01'),
('GUINEA', 'Syli', 'GNE', '324', NULL, '1989-12'),
('ISRAEL', 'Pound', 'ILP', '376', NULL, '1978 to 1981'),
('MADAGASCAR', 'Malagasy Franc', 'MGF', '450', NULL, '2004-12'),
('SAINT PIERRE AND MIQUELON', 'French Franc', 'FRF', '250', NULL, '2002-03'),
('SPAIN', '''"A" Account (convertible Peseta Account)''', 'ESB', '995', NULL, '1994-12'),
('SWAZILAND', 'Lilangeni', 'SZL', '748', NULL, '2018-08'),
('TAJIKISTAN', 'Tajik Ruble', 'TJR', '762', NULL, '2001-04'),
('BONAIRE, SINT EUSTATIUS AND SABA', 'US Dollar', 'USD', '840', '2', NULL),
('CAMEROON', 'CFA Franc BEAC', 'XAF', '950', '0', NULL),
('DJIBOUTI', 'Djibouti Franc', 'DJF', '262', '0', NULL),
('GUATEMALA', 'Quetzal', 'GTQ', '320', '2', NULL),
('IRELAND', 'Euro', 'EUR', '978', '2', NULL),
('NETHERLANDS (THE)', 'Euro', 'EUR', '978', '2', NULL),
('NORTHERN MARIANA ISLANDS (THE)', 'US Dollar', 'USD', '840', '2', NULL),
('PANAMA', 'US Dollar', 'USD', '840', '2', NULL),
('TOKELAU', 'New Zealand Dollar', 'NZD', '554', '2', NULL),
('BURMA', 'Kyat', 'BUK', '104', NULL, '1990-02'),
('FRANCE', 'French Franc', 'FRF', '250', NULL, '2002-03'),
('MEXICO', 'Mexican Peso', 'MXP', '484', NULL, '1993-01'),
('NETHERLANDS', 'Netherlands Guilder', 'NLG', '528', NULL, '2002-03'),
('UGANDA', 'Old Shilling', 'UGW', '800', NULL, '1989 to 1990'),
('YUGOSLAVIA', 'Yugoslavian Dinar', 'YUN', '890', NULL, '1995-11'),
('BAHRAIN', 'Bahraini Dinar', 'BHD', '048', '3', NULL),
('CHILE', 'Unidad de Fomento', 'CLF', '990', '4', NULL),
('ERITREA', 'Nakfa', 'ERN', '232', '2', NULL),
('FINLAND', 'Euro', 'EUR', '978', '2', NULL),
('GUYANA', 'Guyana Dollar', 'GYD', '328', '2', NULL),
('MALTA', 'Euro', 'EUR', '978', '2', NULL),
('NORFOLK ISLAND', 'Australian Dollar', 'AUD', '036', '2', NULL),
('NORWAY', 'Norwegian Krone', 'NOK', '578', '2', NULL),
('PANAMA', 'Balboa', 'PAB', '590', '2', NULL),
('SENEGAL', 'CFA Franc BCEAO', 'XOF', '952', '0', NULL),
('ZZ06_Testing_Code', 'Codes specifically reserved for testing purposes', 'XTS', '963', '-', NULL),
('ARGENTINA', 'Peso Argentino', 'ARP', '032', NULL, '1985-07'),
('LITHUANIA', 'Talonas', 'LTT', '440', NULL, '1993-07'),
('MOZAMBIQUE', 'Mozambique Metical', 'MZM', '508', NULL, '2006-06'),
('PORTUGAL', 'Portuguese Escudo', 'PTE', '620', NULL, '2002-03'),
('SERBIA AND MONTENEGRO', 'Serbian Dinar', 'CSD', '891', NULL, '2006-10'),
('SIERRA LEONE', 'Leone', 'SLL', '694', NULL, '2023-12'),
('ZAMBIA', 'Zambian Kwacha', 'ZMK', '894', NULL, '2012-12'),
('BAHAMAS (THE)', 'Bahamian Dollar', 'BSD', '044', '2', NULL),
('BURKINA FASO', 'CFA Franc BCEAO', 'XOF', '952', '0', NULL),
('GABON', 'CFA Franc BEAC', 'XAF', '950', '0', NULL),
('HEARD ISLAND AND McDONALD ISLANDS', 'Australian Dollar', 'AUD', '036', '2', NULL),
('INDONESIA', 'Rupiah', 'IDR', '360', '2', NULL),
('MARSHALL ISLANDS (THE)', 'US Dollar', 'USD', '840', '2', NULL),
('MOLDOVA (THE REPUBLIC OF)', 'Moldovan Leu', 'MDL', '498', '2', NULL),
('MOZAMBIQUE', 'Mozambique Metical', 'MZN', '943', '2', NULL),
('SOUTH SUDAN', 'South Sudanese Pound', 'SSP', '728', '2', NULL),
('URUGUAY', 'Uruguay Peso en Unidades Indexadas (UI)', 'UYI', '940', '0', NULL),
('ARMENIA', 'Russian Ruble', 'RUR', '810', NULL, '1994-08'),
('BELARUS', 'Belarusian Ruble', 'BYR', '974', NULL, '2017-01'),
('CZECHOSLOVAKIA', 'Krona A/53', 'CSJ', '203', NULL, '1989 to 1990'),
('GUINEA-BISSAU', 'Guinea Escudo', 'GWE', '624', NULL, '1978 to 1981'),
('LUXEMBOURG', 'Luxembourg Franc', 'LUF', '442', NULL, '2002-03'),
('BOUVET ISLAND', 'Norwegian Krone', 'NOK', '578', '2', NULL),
('CÔTE D''IVOIRE', 'CFA Franc BCEAO', 'XOF', '952', '0', NULL),
('CUBA', 'Cuban Peso', 'CUP', '192', '2', NULL),
('GERMANY', 'Euro', 'EUR', '978', '2', NULL),
('MOROCCO', 'Moroccan Dirham', 'MAD', '504', '2', NULL),
('NIGERIA', 'Naira', 'NGN', '566', '2', NULL),
('AFGHANISTAN', 'Afghani', 'AFA', '004', NULL, '2003-01'),
('ECUADOR', 'Sucre', 'ECS', '218', NULL, '2000-09'),
('FINLAND', 'Markka', 'FIM', '246', NULL, '2002-03'),
('PERU', 'Sol', 'PES', '604', NULL, '1986-02'),
('SAINT-BARTHÉLEMY', 'French Franc', 'FRF', '250', NULL, '1999-01'),
('DOMINICA', 'East Caribbean Dollar', 'XCD', '951', '2', NULL),
('MALDIVES', 'Rufiyaa', 'MVR', '462', '2', NULL),
('NEW ZEALAND', 'New Zealand Dollar', 'NZD', '554', '2', NULL),
('PAPUA NEW GUINEA', 'Kina', 'PGK', '598', '2', NULL),
('PITCAIRN', 'New Zealand Dollar', 'NZD', '554', '2', NULL),
('UNITED ARAB EMIRATES (THE)', 'UAE Dirham', 'AED', '784', '2', NULL),
('UZBEKISTAN', 'Uzbekistan Sum', 'UZS', '860', '2', NULL),
('ZIMBABWE', 'Zimbabwe Gold', 'ZWG', '924', '2', NULL),
('AZERBAIJAN', 'Azerbaijan Manat', 'AYM', '945', NULL, '2005-10'),
('BELARUS', 'Russian Ruble', 'RUR', '810', NULL, '1994-06'),
('BOLIVIA', 'Peso boliviano', 'BOP', '068', NULL, '1987-02'),
('BULGARIA', 'Lev A/52', 'BGJ', '100', NULL, '1989 to 1990'),
('GUADELOUPE', 'French Franc', 'FRF', '250', NULL, '2002-03'),
('SINT MAARTEN (DUTCH PART)', 'Netherlands Antillean Guilder', 'ANG', '532', NULL, '2025-03'),
('SLOVAKIA', 'Slovak Koruna', 'SKK', '703', NULL, '2009-01'),
('ARMENIA', 'Armenian Dram', 'AMD', '051', '2', NULL),
('BELGIUM', 'Euro', 'EUR', '978', '2', NULL),
('GIBRALTAR', 'Gibraltar Pound', 'GIP', '292', '2', NULL),
('NORTH MACEDONIA', 'Denar', 'MKD', '807', '2', NULL),
('MALAYSIA', 'Malaysian Ringgit', 'MYR', '458', '2', NULL),
('MEXICO', 'Mexican Peso', 'MXN', '484', '2', NULL),
('MICRONESIA (FEDERATED STATES OF)', 'US Dollar', 'USD', '840', '2', NULL),
('NIGER (THE)', 'CFA Franc BCEAO', 'XOF', '952', '0', NULL),
('RUSSIAN FEDERATION (THE)', 'Russian Ruble', 'RUB', '643', '2', NULL),
('SOUTH AFRICA', 'Rand', 'ZAR', '710', '2', NULL),
('SWITZERLAND', 'Swiss Franc', 'CHF', '756', '2', NULL),
('THAILAND', 'Baht', 'THB', '764', '2', NULL),
('TOGO', 'CFA Franc BCEAO', 'XOF', '952', '0', NULL),
('TURKMENISTAN', 'Turkmenistan New Manat', 'TMT', '934', '2', NULL),
('ARGENTINA', 'Peso', 'ARY', '032', NULL, '1989 to 1990'),
('EUROPEAN MONETARY CO-OPERATION FUND (EMCF)', 'European Currency Unit (E.C.U)', 'XEU', '954', NULL, '1999-01'),
('ITALY', 'Italian Lira', 'ITL', '380', NULL, '2002-03'),
('BHUTAN', 'Ngultrum', 'BTN', '064', '2', NULL),
('CHINA', 'Yuan Renminbi', 'CNY', '156', '2', NULL),
('EL SALVADOR', 'El Salvador Colon', 'SVC', '222', '2', NULL),
('GREECE', 'Euro', 'EUR', '978', '2', NULL),
('HONG KONG', 'Hong Kong Dollar', 'HKD', '344', '2', NULL),
('LESOTHO', 'Loti', 'LSL', '426', '2', NULL),
('MAURITIUS', 'Mauritius Rupee', 'MUR', '480', '2', NULL),
('NAMIBIA', 'Rand', 'ZAR', '710', '2', NULL),
('NIUE', 'New Zealand Dollar', 'NZD', '554', '2', NULL),
('ZZ08_Gold', 'Gold', 'XAU', '959', '-', NULL),
('CROATIA', 'Croatian Kuna', 'HRK', '191', NULL, '2015-06'),
('CUBA', 'Peso Convertible', 'CUC', '931', NULL, '2021-06'),
('LAO', 'Pathet Lao Kip', 'LAJ', '418', NULL, '1979-12'),
('UZBEKISTAN', 'Russian Ruble', 'RUR', '810', NULL, '1994-07'),
('BARBADOS', 'Barbados Dollar', 'BBD', '052', '2', NULL),
('CHAD', 'CFA Franc BEAC', 'XAF', '950', '0', NULL),
('COCOS (KEELING) ISLANDS (THE)', 'Australian Dollar', 'AUD', '036', '2', NULL),
('EL SALVADOR', 'US Dollar', 'USD', '840', '2', NULL),
('LUXEMBOURG', 'Euro', 'EUR', '978', '2', NULL),
('POLAND', 'Zloty', 'PLN', '985', '2', NULL),
('PUERTO RICO', 'US Dollar', 'USD', '840', '2', NULL),
('SAO TOME AND PRINCIPE', 'Dobra', 'STN', '930', '2', NULL),
('SVALBARD AND JAN MAYEN', 'Norwegian Krone', 'NOK', '578', '2', NULL),
('ZZ01_Bond Markets Unit European_EURCO', 'Bond Markets Unit European Composite Unit (EURCO)', 'XBA', '955', '-', NULL),
('ZZ02_Bond Markets Unit European_EMU-6', 'Bond Markets Unit European Monetary Unit (E.M.U.-6)', 'XBB', '956', '-', NULL),
('ANDORRA', 'Andorran Peseta', 'ADP', '020', NULL, '2003-07'),
('GUINEA-BISSAU', 'Guinea-Bissau Peso', 'GWP', '624', NULL, '1997-05'),
('HOLY SEE (VATICAN CITY STATE)', 'Italian Lira', 'ITL', '380', NULL, '2002-03'),
('IRELAND', 'Irish Pound', 'IEP', '372', NULL, '2002-03'),
('ISRAEL', 'Old Shekel', 'ILR', '376', NULL, '1989 to 1990'),
('LUXEMBOURG', 'Luxembourg Convertible Franc', 'LUC', '989', NULL, '1990-03'),
('LUXEMBOURG', 'Luxembourg Financial Franc', 'LUL', '988', NULL, '1990-03'),
('ROMANIA', 'Old Leu', 'ROL', '642', NULL, '2005-06'),
('TAJIKISTAN', 'Russian Ruble', 'RUR', '810', NULL, '1995-05'),
('VENEZUELA', 'Bolivar Fuerte', 'VEF', '937', NULL, '2011-12'),
('ZIMBABWE', 'Zimbabwe Dollar (new)', 'ZWN', '942', NULL, '2006-09'),
('ÅLAND ISLANDS', 'Euro', 'EUR', '978', '2', NULL),
('BOLIVIA (PLURINATIONAL STATE OF)', 'Boliviano', 'BOB', '068', '2', NULL),
('FRENCH SOUTHERN TERRITORIES (THE)', 'Euro', 'EUR', '978', '2', NULL),
('GUERNSEY', 'Pound Sterling', 'GBP', '826', '2', NULL),
('LITHUANIA', 'Euro', 'EUR', '978', '2', NULL),
('MADAGASCAR', 'Malagasy Ariary', 'MGA', '969', '2', NULL),
('OMAN', 'Rial Omani', 'OMR', '512', '3', NULL),
('RWANDA', 'Rwanda Franc', 'RWF', '646', '0', NULL),
('SAN MARINO', 'Euro', 'EUR', '978', '2', NULL),
('SINGAPORE', 'Singapore Dollar', 'SGD', '702', '2', NULL),
('TIMOR-LESTE', 'US Dollar', 'USD', '840', '2', NULL),
('TONGA', 'Pa''anga', 'TOP', '776', '2', NULL),
('WALLIS AND FUTUNA', 'CFP Franc', 'XPF', '953', '0', NULL),
('ROMANIA', 'New Romanian Leu', 'RON', '946', NULL, '2015-06'),
('SOUTH AFRICA', 'Financial Rand', 'ZAL', '991', NULL, '1995-03'),
('SPAIN', 'Spanish Peseta', 'ESP', '724', NULL, '2002-03'),
('VENEZUELA', 'Bolivar', 'VEB', '862', NULL, '2008-01'),
('VIETNAM', 'Old Dong', 'VNC', '704', NULL, '1989-1990'),
('ANGOLA', 'Kwanza', 'AOA', '973', '2', NULL),
('BRITISH INDIAN OCEAN TERRITORY (THE)', 'US Dollar', 'USD', '840', '2', NULL),
('PHILIPPINES (THE)', 'Philippine Peso', 'PHP', '608', '2', NULL),
('SAMOA', 'Tala', 'WST', '882', '2', NULL),
('BOSNIA AND HERZEGOVINA', 'Dinar', 'BAD', '070', NULL, '1998-07'),
('BRAZIL', 'New Cruzado', 'BRN', '076', NULL, '1990-03'),
('BRAZIL', 'Cruzeiro Real', 'BRR', '987', NULL, '1994-07'),
('CYPRUS', 'Cyprus Pound', 'CYP', '196', NULL, '2008-01'),
('GUINEA', 'Syli', 'GNS', '324', NULL, '1986-02'),
('KAZAKHSTAN', 'Russian Ruble', 'RUR', '810', NULL, '1994-05'),
('LITHUANIA', 'Lithuanian Litas', 'LTL', '440', NULL, '2014-12'),
('MALTA', 'Maltese Pound', 'MTP', '470', NULL, '1983-06'),
('TURKMENISTAN', 'Russian Ruble', 'RUR', '810', NULL, '1993-10'),
('URUGUAY', 'Old Uruguay Peso', 'UYN', '858', NULL, '1989-12'),
('ANDORRA', 'Euro', 'EUR', '978', '2', NULL),
('BELARUS', 'Belarusian Ruble', 'BYN', '933', '2', NULL),
('ICELAND', 'Iceland Krona', 'ISK', '352', '0', NULL),
('KOREA (THE DEMOCRATIC PEOPLE''S REPUBLIC OF)', 'North Korean Won', 'KPW', '408', '2', NULL),
('LIBERIA', 'Liberian Dollar', 'LRD', '430', '2', NULL),
('MARTINIQUE', 'Euro', 'EUR', '978', '2', NULL),
('SAINT LUCIA', 'East Caribbean Dollar', 'XCD', '951', '2', NULL),
('UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)', 'Pound Sterling', 'GBP', '826', '2', NULL),
('ARGENTINA', 'Austral', 'ARA', '032', NULL, '1992-01'),
('GERMAN DEMOCRATIC REPUBLIC', 'Mark der DDR', 'DDM', '278', NULL, '1990-07 to 1990-09'),
('GHANA', 'Cedi', 'GHC', '288', NULL, '2008-01'),
('MOLDOVA, REPUBLIC OF', 'Russian Ruble', 'RUR', '810', NULL, '1993-12'),
('NETHERLANDS ANTILLES', 'Netherlands Antillean Guilder', 'ANG', '532', NULL, '2010-10'),
('SUDAN', 'Sudanese Pound', 'SDP', '736', NULL, '1998-06'),
('UKRAINE', 'Karbovanet', 'UAK', '804', NULL, '1996-09'),
('AZERBAIJAN', 'Azerbaijan Manat', 'AZN', '944', '2', NULL),
('CZECHIA', 'Czech Koruna', 'CZK', '203', '2', NULL),
('LAO PEOPLE''S DEMOCRATIC REPUBLIC (THE)', 'Lao Kip', 'LAK', '418', '2', NULL),
('UGANDA', 'Uganda Shilling', 'UGX', '800', '0', NULL),
('UNITED STATES OF AMERICA (THE)', 'US Dollar (Next day)', 'USN', '997', '2', NULL),
('ZZ10_Platinum', 'Platinum', 'XPT', '962', '-', NULL),
('BRAZIL', 'Cruzeiro', 'BRB', '076', NULL, '1986-03'),
('BULGARIA', 'Lev', 'BGL', '100', NULL, '2003-11'),
('LESOTHO', 'Loti', 'LSM', '426', NULL, '1985-05'),
('PERU', 'Sol', 'PEH', '604', NULL, '1989 to 1990'),
('URUGUAY', 'Uruguayan Peso', 'UYP', '858', NULL, '1993-03'),
('ZZ02_RINET Funds Code', 'RINET Funds Code', 'XRE', NULL, NULL, '1999-11'),
('AUSTRALIA', 'Australian Dollar', 'AUD', '036', '2', NULL),
('EGYPT', 'Egyptian Pound', 'EGP', '818', '2', NULL),
('ESWATINI', 'Lilangeni', 'SZL', '748', '2', NULL),
('ISLE OF MAN', 'Pound Sterling', 'GBP', '826', '2', NULL),
('JAPAN', 'Yen', 'JPY', '392', '0', NULL),
('JERSEY', 'Pound Sterling', 'GBP', '826', '2', NULL),
('MACAO', 'Pataca', 'MOP', '446', '2', NULL),
('MYANMAR', 'Kyat', 'MMK', '104', '2', NULL),
('ROMANIA', 'Romanian Leu', 'RON', '946', '2', NULL),
('SAINT MARTIN (FRENCH PART)', 'Euro', 'EUR', '978', '2', NULL),
('SLOVENIA', 'Euro', 'EUR', '978', '2', NULL),
('VENEZUELA (BOLIVARIAN REPUBLIC OF)', 'Bolívar Soberano', 'VED', '926', '2', NULL),
('VIET NAM', 'Dong', 'VND', '704', '0', NULL),
('ANGOLA', 'New Kwanza', 'AON', '024', NULL, '2000-02'),
('FRENCH  GUIANA', 'French Franc', 'FRF', '250', NULL, '2002-03'),
('MALTA', 'Maltese Lira', 'MTL', '470', NULL, '2008-01'),
('MAURITANIA', 'Ouguiya', 'MRO', '478', NULL, '2017-12'),
('MONACO', 'French Franc', 'FRF', '250', NULL, '2002-03'),
('MOZAMBIQUE', 'Mozambique Escudo', 'MZE', '508', NULL, '1978 to 1981'),
('SURINAME', 'Surinam Guilder', 'SRG', '740', NULL, '2003-12'),
('TURKEY', 'New Turkish Lira', 'TRY', '949', NULL, '2009-01'),
('YEMEN, DEMOCRATIC', 'Yemeni Dinar', 'YDD', '720', NULL, '1991-09'),
('ZIMBABWE', 'Zimbabwe Dollar', 'ZWL', '932', NULL, '2024-09'),
('AFGHANISTAN', 'Afghani', 'AFN', '971', '2', NULL),
('COMOROS (THE)', 'Comorian Franc', 'KMF', '174', '0', NULL),
('GAMBIA (THE)', 'Dalasi', 'GMD', '270', '2', NULL),
('IRAN (ISLAMIC REPUBLIC OF)', 'Iranian Rial', 'IRR', '364', '2', NULL),
('ISRAEL', 'New Israeli Sheqel', 'ILS', '376', '2', NULL),
('KYRGYZSTAN', 'Som', 'KGS', '417', '2', NULL),
('NEPAL', 'Nepalese Rupee', 'NPR', '524', '2', NULL),
('SAUDI ARABIA', 'Saudi Riyal', 'SAR', '682', '2', NULL),
('SIERRA LEONE', 'Leone', 'SLE', '925', '2', NULL),
('VENEZUELA (BOLIVARIAN REPUBLIC OF)', 'Bolívar Soberano', 'VES', '928', '2', NULL),
('ZZ07_No_Currency', 'The codes assigned for transactions where no currency is involved', 'XXX', '999', '-', NULL),
('ANDORRA', 'French Franc', 'FRF', '250', NULL, '2002-03'),
('CROATIA', 'Croatian Dinar', 'HRD', '191', NULL, '1995-01'),
('MAYOTTE', 'French Franc', 'FRF', '250', NULL, '2002-03'),
('ROMANIA', 'Leu A/52', 'ROK', '642', NULL, '1989 to 1990'),
('COLOMBIA', 'Unidad de Valor Real', 'COU', '970', '2', NULL),
('GUADELOUPE', 'Euro', 'EUR', '978', '2', NULL),
('HOLY SEE (THE)', 'Euro', 'EUR', '978', '2', NULL),
('KUWAIT', 'Kuwaiti Dinar', 'KWD', '414', '3', NULL),
('LEBANON', 'Lebanese Pound', 'LBP', '422', '2', NULL),
('SAINT BARTHÉLEMY', 'Euro', 'EUR', '978', '2', NULL),
('TÜRKİYE', 'Turkish Lira', 'TRY', '949', '2', NULL),
('AUSTRIA', 'Schilling', 'ATS', '040', NULL, '2002-03'),
('AZERBAIJAN', 'Russian Ruble', 'RUR', '810', NULL, '1994-08'),
('BELARUS', 'Belarusian Ruble', 'BYB', '112', NULL, '2001-01'),
('MALAWI', 'Kwacha', 'MWK', '454', NULL, '2016-02'),
('ZIMBABWE', 'Zimbabwe Dollar', 'ZWD', '716', NULL, '2008-08'),
('BHUTAN', 'Indian Rupee', 'INR', '356', '2', NULL),
('BOSNIA AND HERZEGOVINA', 'Convertible Mark', 'BAM', '977', '2', NULL),
('COLOMBIA', 'Colombian Peso', 'COP', '170', '2', NULL),
('ESTONIA', 'Euro', 'EUR', '978', '2', NULL),
('HUNGARY', 'Forint', 'HUF', '348', '2', NULL),
('JAMAICA', 'Jamaican Dollar', 'JMD', '388', '2', NULL),
('LIBYA', 'Libyan Dinar', 'LYD', '434', '3', NULL),
('NAURU', 'Australian Dollar', 'AUD', '036', '2', NULL),
('UNITED STATES OF AMERICA (THE)', 'US Dollar', 'USD', '840', '2', NULL),
('ZZ03_Bond Markets Unit European_EUA-9', 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)', 'XBC', '957', '-', NULL),
('MALI', 'Mali Franc', 'MLF', '466', NULL, '1984-11'),
('SUDAN', 'Sudanese Dinar', 'SDD', '736', NULL, '2007-07'),
('ZIMBABWE', 'Rhodesian Dollar', 'ZWC', '716', NULL, '1989-12'),
('CROATIA', 'Euro', 'EUR', '978', '2', NULL),
('HAITI', 'Gourde', 'HTG', '332', '2', NULL),
('KOREA (THE REPUBLIC OF)', 'Won', 'KRW', '410', '0', NULL),
('MAYOTTE', 'Euro', 'EUR', '978', '2', NULL),
('PORTUGAL', 'Euro', 'EUR', '978', '2', NULL),
('QATAR', 'Qatari Rial', 'QAR', '634', '2', NULL),
('VIRGIN ISLANDS (U.S.)', 'US Dollar', 'USD', '840', '2', NULL),
('FRENCH SOUTHERN TERRITORIES', 'French Franc', 'FRF', '250', NULL, '2002-03'),
('NICARAGUA', 'Cordoba', 'NIC', '558', NULL, '1990-10'),
('SLOVENIA', 'Tolar', 'SIT', '705', NULL, '2007-01'),
('SOUTH SUDAN', 'Sudanese Pound', 'SDG', '938', NULL, '2012-09'),
('SWITZERLAND', 'WIR Franc (for electronic)', 'CHC', '948', NULL, '2004-11'),
('ALGERIA', 'Algerian Dinar', 'DZD', '012', '2', NULL),
('ARUBA', 'Aruban Florin', 'AWG', '533', '2', NULL),
('CANADA', 'Canadian Dollar', 'CAD', '124', '2', NULL),
('CAYMAN ISLANDS (THE)', 'Cayman Islands Dollar', 'KYD', '136', '2', NULL),
('EQUATORIAL GUINEA', 'CFA Franc BEAC', 'XAF', '950', '0', NULL),
('GREENLAND', 'Danish Krone', 'DKK', '208', '2', NULL),
('SPAIN', 'Euro', 'EUR', '978', '2', NULL),
('SYRIAN ARAB REPUBLIC', 'Syrian Pound', 'SYP', '760', '2', NULL),
('TANZANIA, UNITED REPUBLIC OF', 'Tanzanian Shilling', 'TZS', '834', '2', NULL),
('ÅLAND ISLANDS', 'Markka', 'FIM', '246', NULL, '2002-03'),
('KYRGYZSTAN', 'Russian Ruble', 'RUR', '810', NULL, '1993-01'),
('MALDIVES', 'Maldive Rupee', 'MVQ', '462', NULL, '1989-12'),
('UNION OF SOVIET SOCIALIST REPUBLICS', 'Rouble', 'SUR', '810', NULL, '1990-12'),
('UNITED STATES', 'US Dollar (Same day)', 'USS', '998', NULL, '2014-03'),
('ZAIRE', 'New Zaire', 'ZRN', '180', NULL, '1999-06'),
('BERMUDA', 'Bermudian Dollar', 'BMD', '060', '2', NULL),
('BOLIVIA (PLURINATIONAL STATE OF)', 'Mvdol', 'BOV', '984', '2', NULL),
('BOTSWANA', 'Pula', 'BWP', '072', '2', NULL),
('BURUNDI', 'Burundi Franc', 'BIF', '108', '0', NULL),
('DOMINICAN REPUBLIC (THE)', 'Dominican Peso', 'DOP', '214', '2', NULL),
('FRENCH POLYNESIA', 'CFP Franc', 'XPF', '953', '0', NULL),
('GUINEA-BISSAU', 'CFA Franc BCEAO', 'XOF', '952', '0', NULL),
('KAZAKHSTAN', 'Tenge', 'KZT', '398', '2', NULL),
('SERBIA', 'Serbian Dinar', 'RSD', '941', '2', NULL),
('ZAMBIA', 'Zambian Kwacha', 'ZMW', '967', '2', NULL),
('BELGIUM', 'Belgian Franc', 'BEF', '056', NULL, '2002-03'),
('BRAZIL', 'Cruzado', 'BRC', '076', NULL, '1989-02'),
('CZECHOSLOVAKIA', 'Koruna', 'CSK', '200', NULL, '1993-03'),
('EQUATORIAL GUINEA', 'Ekwele', 'GQE', '226', NULL, '1986-06'),
('GHANA', 'Ghana Cedi', 'GHP', '939', NULL, '2007-06'),
('ICELAND', 'Old Krona', 'ISJ', '352', NULL, '1989 to 1990'),
('LATVIA', 'Latvian Lats', 'LVL', '428', NULL, '2014-01'),
('RUSSIAN FEDERATION', 'Russian Ruble', 'RUR', '810', NULL, '2004-01'),
('SERBIA AND MONTENEGRO', 'Euro', 'EUR', '978', NULL, '2006-10'),
('TIMOR-LESTE', 'Timor Escudo', 'TPE', '626', NULL, '2002-11'),
('UGANDA', 'Uganda Shilling', 'UGS', '800', NULL, '1987-05'),
('ZZ01_Gold-Franc', 'Gold-Franc', 'XFO', NULL, NULL, '2006-10'),
('BELIZE', 'Belize Dollar', 'BZD', '084', '2', NULL),
('CYPRUS', 'Euro', 'EUR', '978', '2', NULL),
('FALKLAND ISLANDS (THE) [MALVINAS]', 'Falkland Islands Pound', 'FKP', '238', '2', NULL),
('MEXICO', 'Mexican Unidad de Inversion (UDI)', 'MXV', '979', '2', NULL),
('SOLOMON ISLANDS', 'Solomon Islands Dollar', 'SBD', '090', '2', NULL),
('SWITZERLAND', 'WIR Franc', 'CHW', '948', '2', NULL),
('TAIWAN (PROVINCE OF CHINA)', 'New Taiwan Dollar', 'TWD', '901', '2', NULL),
('TRINIDAD AND TOBAGO', 'Trinidad and Tobago Dollar', 'TTD', '780', '2', NULL),
('URUGUAY', 'Peso Uruguayo', 'UYU', '858', '2', NULL),
('ANDORRA', 'Spanish Peseta', 'ESP', '724', NULL, '2002-03'),
('BELGIUM', 'Convertible Franc', 'BEC', '993', NULL, '1990-03'),
('BELGIUM', 'Financial Franc', 'BEL', '992', NULL, '1990-03'),
('GEORGIA', 'Russian Ruble', 'RUR', '810', NULL, '1994-04'),
('GREECE', 'Drachma', 'GRD', '300', NULL, '2002-03'),
('PERU', 'Nuevo Sol', 'PEN', '604', NULL, '2015-12'),
('TIMOR-LESTE', 'Rupiah', 'IDR', '360', NULL, '2002-07'),
('ZAIRE', 'Zaire', 'ZRZ', '180', NULL, '1994-02'),
('AUSTRIA', 'Euro', 'EUR', '978', '2', NULL),
('DENMARK', 'Danish Krone', 'DKK', '208', '2', NULL),
('ITALY', 'Euro', 'EUR', '978', '2', NULL),
('PERU', 'Sol', 'PEN', '604', '2', NULL),
('RÉUNION', 'Euro', 'EUR', '978', '2', NULL),
('SAINT KITTS AND NEVIS', 'East Caribbean Dollar', 'XCD', '951', '2', NULL),
('SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE"', 'Sucre', 'XSU', '994', '-', NULL),
('TUNISIA', 'Tunisian Dinar', 'TND', '788', '3', NULL),
('UNITED STATES MINOR OUTLYING ISLANDS (THE)', 'US Dollar', 'USD', '840', '2', NULL),
('VANUATU', 'Vatu', 'VUV', '548', '0', NULL),
('PERU', 'Inti', 'PEI', '604', NULL, '1991-07'),
('POLAND', 'Zloty', 'PLZ', '616', NULL, '1997-01'),
('SPAIN', 'Spanish Peseta', 'ESA', '996', NULL, '1978 to 1981');