/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWishlistsIndexRouteImport } from './routes/_authenticated/wishlists.index'
import { Route as WishlistsSharedIdRouteImport } from './routes/wishlists.shared.$id'
import { Route as AuthenticatedWishlistsIdRouteImport } from './routes/_authenticated/wishlists.$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWishlistsIndexRoute =
  AuthenticatedWishlistsIndexRouteImport.update({
    id: '/wishlists/',
    path: '/wishlists/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const WishlistsSharedIdRoute = WishlistsSharedIdRouteImport.update({
  id: '/wishlists/shared/$id',
  path: '/wishlists/shared/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWishlistsIdRoute =
  AuthenticatedWishlistsIdRouteImport.update({
    id: '/wishlists/$id',
    path: '/wishlists/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wishlists/$id': typeof AuthenticatedWishlistsIdRoute
  '/wishlists/shared/$id': typeof WishlistsSharedIdRoute
  '/wishlists': typeof AuthenticatedWishlistsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wishlists/$id': typeof AuthenticatedWishlistsIdRoute
  '/wishlists/shared/$id': typeof WishlistsSharedIdRoute
  '/wishlists': typeof AuthenticatedWishlistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/wishlists/$id': typeof AuthenticatedWishlistsIdRoute
  '/wishlists/shared/$id': typeof WishlistsSharedIdRoute
  '/_authenticated/wishlists/': typeof AuthenticatedWishlistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/wishlists/$id' | '/wishlists/shared/$id' | '/wishlists'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/wishlists/$id' | '/wishlists/shared/$id' | '/wishlists'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/wishlists/$id'
    | '/wishlists/shared/$id'
    | '/_authenticated/wishlists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  WishlistsSharedIdRoute: typeof WishlistsSharedIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wishlists/': {
      id: '/_authenticated/wishlists/'
      path: '/wishlists'
      fullPath: '/wishlists'
      preLoaderRoute: typeof AuthenticatedWishlistsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/wishlists/shared/$id': {
      id: '/wishlists/shared/$id'
      path: '/wishlists/shared/$id'
      fullPath: '/wishlists/shared/$id'
      preLoaderRoute: typeof WishlistsSharedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wishlists/$id': {
      id: '/_authenticated/wishlists/$id'
      path: '/wishlists/$id'
      fullPath: '/wishlists/$id'
      preLoaderRoute: typeof AuthenticatedWishlistsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedWishlistsIdRoute: typeof AuthenticatedWishlistsIdRoute
  AuthenticatedWishlistsIndexRoute: typeof AuthenticatedWishlistsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedWishlistsIdRoute: AuthenticatedWishlistsIdRoute,
  AuthenticatedWishlistsIndexRoute: AuthenticatedWishlistsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  WishlistsSharedIdRoute: WishlistsSharedIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
